export declare const list: import("convex/server").RegisteredQuery<"public", {
    status?: "PAID" | "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    propertyId?: import("convex/values").GenericId<"properties">;
    isDirect?: boolean;
    limit?: number;
    cursor?: import("convex/values").GenericId<"bookings">;
    userId?: import("convex/values").GenericId<"user">;
    month?: string;
    year?: string;
}, Promise<{
    bookings: {
        property: {
            id: import("convex/values").GenericId<"properties">;
            title: string;
            location: string;
            image: any;
        };
        _id: import("convex/values").GenericId<"bookings">;
        _creationTime: number;
        numeroMascotas?: number;
        costoMascotas?: number;
        observaciones?: string;
        horaEntrada?: string;
        horaSalida?: string;
        city?: string;
        purpose?: string;
        reference?: string;
        address?: string;
        isDirect?: boolean;
        currency?: string;
        userId?: import("convex/values").GenericId<"contacts">;
        multimedia?: {
            name: string;
            type: string;
            url: string;
        }[];
        updatedAt?: number;
        personasAdicionales?: number;
        tieneMascotas?: boolean;
        detallesMascotas?: string;
        costoPersonasAdicionales?: number;
        costoPersonalServicio?: number;
        depositoGarantia?: number;
        depositoAseo?: number;
        discountCode?: string;
        discountAmount?: number;
        transactionId?: string;
        isDirectBooking?: boolean;
        googleEventId?: string;
        googleCalendarId?: string;
        status: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        fechaEntrada: number;
        fechaSalida: number;
        propertyId: import("convex/values").GenericId<"properties">;
        temporada: string;
        nombreCompleto: string;
        cedula: string;
        celular: string;
        correo: string;
        numeroPersonas: number;
        precioTotal: number;
        createdAt: number;
        numeroNoches: number;
        subtotal: number;
        paymentStatus: "PAID" | "PENDING" | "PARTIAL" | "REFUNDED";
    }[];
    hasMore: boolean;
    nextCursor: import("convex/values").GenericId<"bookings">;
}>>;
export declare const getById: import("convex/server").RegisteredQuery<"public", {
    id: import("convex/values").GenericId<"bookings">;
}, Promise<{
    property: {
        _id: import("convex/values").GenericId<"properties">;
        _creationTime: number;
        code?: string;
        rating?: number;
        priceEspeciales?: number;
        active?: boolean;
        visible?: boolean;
        reservable?: boolean;
        isFavorite?: boolean;
        priceOriginal?: number;
        video?: string;
        contractTemplateUrl?: string;
        featuredIcons?: import("convex/values").GenericId<"iconography">[];
        zoneOrder?: string[];
        slug?: string;
        reviewsCount?: number;
        priceRawBase?: string;
        priceRawBaja?: string;
        priceRawMedia?: string;
        priceRawAlta?: string;
        priceRawEspeciales?: string;
        type: "FINCA" | "CASA_CAMPESTRE" | "VILLA" | "HACIENDA" | "QUINTA" | "APARTAMENTO" | "CASA" | "CASA_PRIVADA" | "CASA_EN_CONJUNTO_CERRADO" | "VILLA_PRIVADA" | "CONDOMINIO" | "CASA_BOUTIQUE" | "YATE" | "ISLA" | "GLAMPING";
        title: string;
        description: string;
        location: string;
        capacity: number;
        lat: number;
        lng: number;
        priceBase: number;
        priceBaja: number;
        priceMedia: number;
        priceAlta: number;
        category: "ECONOMICA" | "ESTANDAR" | "PREMIUM" | "LUJO" | "ECOTURISMO" | "CON_PISCINA" | "CERCA_BOGOTA" | "GRUPOS_GRANDES" | "VIP";
        createdAt: number;
        updatedAt: number;
    };
    payments: {
        _id: import("convex/values").GenericId<"payments">;
        _creationTime: number;
        status?: string;
        reference?: string;
        currency?: string;
        transactionId?: string;
        paymentMethod?: string;
        checkoutUrl?: string;
        wompiData?: any;
        boldData?: any;
        receiptUrl?: string;
        verifiedBy?: string;
        verifiedAt?: number;
        notes?: string;
        type: "ABONO_50" | "SALDO_50" | "COMPLETO" | "REEMBOLSO";
        bookingId: import("convex/values").GenericId<"bookings">;
        createdAt: number;
        updatedAt: number;
        amount: number;
    }[];
    _id: import("convex/values").GenericId<"bookings">;
    _creationTime: number;
    numeroMascotas?: number;
    costoMascotas?: number;
    observaciones?: string;
    horaEntrada?: string;
    horaSalida?: string;
    city?: string;
    purpose?: string;
    reference?: string;
    address?: string;
    isDirect?: boolean;
    currency?: string;
    userId?: import("convex/values").GenericId<"contacts">;
    multimedia?: {
        name: string;
        type: string;
        url: string;
    }[];
    updatedAt?: number;
    personasAdicionales?: number;
    tieneMascotas?: boolean;
    detallesMascotas?: string;
    costoPersonasAdicionales?: number;
    costoPersonalServicio?: number;
    depositoGarantia?: number;
    depositoAseo?: number;
    discountCode?: string;
    discountAmount?: number;
    transactionId?: string;
    isDirectBooking?: boolean;
    googleEventId?: string;
    googleCalendarId?: string;
    status: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    fechaEntrada: number;
    fechaSalida: number;
    propertyId: import("convex/values").GenericId<"properties">;
    temporada: string;
    nombreCompleto: string;
    cedula: string;
    celular: string;
    correo: string;
    numeroPersonas: number;
    precioTotal: number;
    createdAt: number;
    numeroNoches: number;
    subtotal: number;
    paymentStatus: "PAID" | "PENDING" | "PARTIAL" | "REFUNDED";
}>>;
export declare const getByReference: import("convex/server").RegisteredQuery<"public", {
    reference: string;
}, Promise<{
    property: {
        _id: import("convex/values").GenericId<"properties">;
        _creationTime: number;
        code?: string;
        rating?: number;
        priceEspeciales?: number;
        active?: boolean;
        visible?: boolean;
        reservable?: boolean;
        isFavorite?: boolean;
        priceOriginal?: number;
        video?: string;
        contractTemplateUrl?: string;
        featuredIcons?: import("convex/values").GenericId<"iconography">[];
        zoneOrder?: string[];
        slug?: string;
        reviewsCount?: number;
        priceRawBase?: string;
        priceRawBaja?: string;
        priceRawMedia?: string;
        priceRawAlta?: string;
        priceRawEspeciales?: string;
        type: "FINCA" | "CASA_CAMPESTRE" | "VILLA" | "HACIENDA" | "QUINTA" | "APARTAMENTO" | "CASA" | "CASA_PRIVADA" | "CASA_EN_CONJUNTO_CERRADO" | "VILLA_PRIVADA" | "CONDOMINIO" | "CASA_BOUTIQUE" | "YATE" | "ISLA" | "GLAMPING";
        title: string;
        description: string;
        location: string;
        capacity: number;
        lat: number;
        lng: number;
        priceBase: number;
        priceBaja: number;
        priceMedia: number;
        priceAlta: number;
        category: "ECONOMICA" | "ESTANDAR" | "PREMIUM" | "LUJO" | "ECOTURISMO" | "CON_PISCINA" | "CERCA_BOGOTA" | "GRUPOS_GRANDES" | "VIP";
        createdAt: number;
        updatedAt: number;
    };
    payments: {
        _id: import("convex/values").GenericId<"payments">;
        _creationTime: number;
        status?: string;
        reference?: string;
        currency?: string;
        transactionId?: string;
        paymentMethod?: string;
        checkoutUrl?: string;
        wompiData?: any;
        boldData?: any;
        receiptUrl?: string;
        verifiedBy?: string;
        verifiedAt?: number;
        notes?: string;
        type: "ABONO_50" | "SALDO_50" | "COMPLETO" | "REEMBOLSO";
        bookingId: import("convex/values").GenericId<"bookings">;
        createdAt: number;
        updatedAt: number;
        amount: number;
    }[];
    _id: import("convex/values").GenericId<"bookings">;
    _creationTime: number;
    numeroMascotas?: number;
    costoMascotas?: number;
    observaciones?: string;
    horaEntrada?: string;
    horaSalida?: string;
    city?: string;
    purpose?: string;
    reference?: string;
    address?: string;
    isDirect?: boolean;
    currency?: string;
    userId?: import("convex/values").GenericId<"contacts">;
    multimedia?: {
        name: string;
        type: string;
        url: string;
    }[];
    updatedAt?: number;
    personasAdicionales?: number;
    tieneMascotas?: boolean;
    detallesMascotas?: string;
    costoPersonasAdicionales?: number;
    costoPersonalServicio?: number;
    depositoGarantia?: number;
    depositoAseo?: number;
    discountCode?: string;
    discountAmount?: number;
    transactionId?: string;
    isDirectBooking?: boolean;
    googleEventId?: string;
    googleCalendarId?: string;
    status: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    fechaEntrada: number;
    fechaSalida: number;
    propertyId: import("convex/values").GenericId<"properties">;
    temporada: string;
    nombreCompleto: string;
    cedula: string;
    celular: string;
    correo: string;
    numeroPersonas: number;
    precioTotal: number;
    createdAt: number;
    numeroNoches: number;
    subtotal: number;
    paymentStatus: "PAID" | "PENDING" | "PARTIAL" | "REFUNDED";
}>>;
export declare const checkAvailability: import("convex/server").RegisteredQuery<"public", {
    fechaEntrada: number;
    fechaSalida: number;
    propertyId: import("convex/values").GenericId<"properties">;
}, Promise<{
    available: boolean;
    conflictingBookings: {
        id: import("convex/values").GenericId<"bookings">;
        fechaEntrada: number;
        fechaSalida: number;
        status: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    }[];
}>>;
export declare const create: import("convex/server").RegisteredMutation<"public", {
    status?: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    numeroMascotas?: number;
    costoMascotas?: number;
    observaciones?: string;
    horaEntrada?: string;
    horaSalida?: string;
    city?: string;
    purpose?: string;
    reference?: string;
    address?: string;
    isDirect?: boolean;
    currency?: string;
    userId?: string;
    multimedia?: {
        name: string;
        type: string;
        url: string;
    }[];
    personasAdicionales?: number;
    tieneMascotas?: boolean;
    detallesMascotas?: string;
    costoPersonasAdicionales?: number;
    costoPersonalServicio?: number;
    depositoGarantia?: number;
    depositoAseo?: number;
    discountCode?: string;
    discountAmount?: number;
    googleEventId?: string;
    googleCalendarId?: string;
    fechaCheckOut?: number;
    fechaEntrada: number;
    fechaSalida: number;
    propertyId: import("convex/values").GenericId<"properties">;
    temporada: string;
    nombreCompleto: string;
    cedula: string;
    celular: string;
    correo: string;
    numeroPersonas: number;
    precioTotal: number;
    numeroNoches: number;
    subtotal: number;
}, Promise<import("convex/values").GenericId<"bookings">>>;
export declare const update: import("convex/server").RegisteredMutation<"public", {
    status?: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    observaciones?: string;
    horaEntrada?: string;
    horaSalida?: string;
    isDirect?: boolean;
    paymentStatus?: "PAID" | "PENDING" | "PARTIAL" | "REFUNDED";
    googleEventId?: string;
    googleCalendarId?: string;
    id: import("convex/values").GenericId<"bookings">;
}, Promise<import("convex/values").GenericId<"bookings">>>;
export declare const cancel: import("convex/server").RegisteredMutation<"public", {
    reason?: string;
    id: import("convex/values").GenericId<"bookings">;
}, Promise<{
    success: boolean;
}>>;
export declare const createPayment: import("convex/server").RegisteredMutation<"public", {
    status?: string;
    reference?: string;
    currency?: string;
    transactionId?: string;
    paymentMethod?: string;
    checkoutUrl?: string;
    wompiData?: any;
    type: "ABONO_50" | "SALDO_50" | "COMPLETO" | "REEMBOLSO";
    bookingId: import("convex/values").GenericId<"bookings">;
    amount: number;
}, Promise<import("convex/values").GenericId<"payments">>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    id: import("convex/values").GenericId<"bookings">;
}, Promise<{
    _id: import("convex/values").GenericId<"bookings">;
    _creationTime: number;
    numeroMascotas?: number;
    costoMascotas?: number;
    observaciones?: string;
    horaEntrada?: string;
    horaSalida?: string;
    city?: string;
    purpose?: string;
    reference?: string;
    address?: string;
    isDirect?: boolean;
    currency?: string;
    userId?: import("convex/values").GenericId<"contacts">;
    multimedia?: {
        name: string;
        type: string;
        url: string;
    }[];
    updatedAt?: number;
    personasAdicionales?: number;
    tieneMascotas?: boolean;
    detallesMascotas?: string;
    costoPersonasAdicionales?: number;
    costoPersonalServicio?: number;
    depositoGarantia?: number;
    depositoAseo?: number;
    discountCode?: string;
    discountAmount?: number;
    transactionId?: string;
    isDirectBooking?: boolean;
    googleEventId?: string;
    googleCalendarId?: string;
    status: "PAID" | "PENDING" | "PENDING_PAYMENT" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
    fechaEntrada: number;
    fechaSalida: number;
    propertyId: import("convex/values").GenericId<"properties">;
    temporada: string;
    nombreCompleto: string;
    cedula: string;
    celular: string;
    correo: string;
    numeroPersonas: number;
    precioTotal: number;
    createdAt: number;
    numeroNoches: number;
    subtotal: number;
    paymentStatus: "PAID" | "PENDING" | "PARTIAL" | "REFUNDED";
}>>;
